### ISSUE TITLE
archan.checker.Archan

### ISSUE THREAD

**Issue by jayvdb** [Pawamoy/django-meerkat#48]
`src/meerkat/marchan/checks.py` refers to `archan.checker.Archan` which doesnt exist in latest released `archan`
```py
from archan.checker import Archan
```

**Comment by pawamoy** [comment]
Indeed. Maybe we should simply set a dependency range for the archan dependency in django-meerkat as a quickfix then. Would you like to send a PR?

**Comment by jayvdb** [comment]
I am sure you could find the correct version quicker than I could.

**Comment by pawamoy** [comment]
Alright, I will try to find some time to do it :wink:

**Comment by pawamoy** [comment]
Will likely not work on this project anymore.
