### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by KyleKing** [Pawamoy/django-meerkat#50]
I haven't used Django before. How do I run this app locally?

```sh
# create/activate venv
python -m pip install -r requirements/base.txt

python manage.py? ..?
```

I found [logan](https://github.com/pawamoy/logan) and [OptimR](https://github.com/gitter-badger/OptimR). I think `meerkat` is meant to be run within an existing django app rather than standalone?

**Comment by pawamoy** [comment]
You are correct! `django-meerkat` is a "Django app", which means it will only work in a Django project. You can actually see it listed in the `INSTALLED_APPS` Django setting: https://github.com/pawamoy/logan/blob/master/logan/logan/settings.py#L35

However one could try to export the interesting parts of the code to implement a standalone version (but what kind of program would it be? a Python CLI generating HTML files or report?).

Happy to answer more questions if you have any!

**Comment by KyleKing** [comment]
I am just interested in a screen shot. I was curious what the UI looked like and maybe porting it to a stand alone HTML output
